site_name: UnBook

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    - scheme: UnBook
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - content.tabs.link

  plugins:
    - glightbox

  font:
  text: Roboto
  code: Roboto Mono

  theme:
    logo: img/logo_UnBook.png

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - attr_list

nav:
  - Início: index.md
  - Documentação:
      - Visão do Produto e Projeto:
          - Histórico de Revisão: visao-de-produto-e-projeto/historico-de-revisao.md
          - Visão Geral do Produto: visao-de-produto-e-projeto/visao-geral-do-produto.md
          - Visão Geral do Projeto: visao-de-produto-e-projeto/visao-geral-do-projeto.md
          - Processo de Desenvolvimento de Software: visao-de-produto-e-projeto/processo-de-desenvolvimento-de-software.md
          - Estratégias de Implementação: visao-de-produto-e-projeto/estrategias.md
      - Backlog do Produto: backlog-do-produto/backlog-do-produto.md
      - Entregas: 
          - Unidade 1:
              - Seminário de Processos e Ciclos de Vida: entregas/seminario.md
              - Video de Apresentação Git Pages: entregas/video-apresentacao.md
      - Lições Aprendidas: 
              - Unidade 1: licoes-aprendidas/licoes-aprendidas-unidade1.md
